name: Node.js CI

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # To make Github uses personal access token
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf ssh://git@github.com/

      - run: npm ci --prefix niceday-api
      - run: npm run build --if-present --prefix niceday-api
      - name: Test niceday-api
        run: npm test --prefix niceday-api
      - name: Run ESLint for niceday-api
        run: npx eslint niceday-api

      - run: npm ci --prefix niceday-broker
      - run: npm run build --if-present --prefix niceday-broker
      - name: Test niceday-broker
        run: npm test --prefix niceday-broker
      - name: Run ESLint for niceday-broker
        run: npx eslint niceday-broker